    curl -X POST --location "http://127.0.0.1:8080/user" \
    -H "Content-Type: application/json" \
    -d "{
          \"id\": \"Salma9128584364\",
          \"name\": \"سلما\",
          \"number\": \"09128584364\",
        }"